spring:
    main.banner-mode: 'off'
    h2.console.enabled: true
    jpa:
        hibernate.ddl-auto: none
        open-in-view: true
    datasource:
        url: ${db.url}
        username: ${db.user}
        password: ${db.password}
