# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
    maven:
        docker:
            - image: circleci/openjdk:11-jdk-node
        steps:
            - checkout
            - run:
                  name: Generate Cache Checksum
                  command: find . -name 'pom.xml' -exec cat {} + | shasum | awk '{print $1}'
                      > /tmp/maven_cache_seed
            - restore_cache:
                  key: maven-{{ checksum "/tmp/maven_cache_seed" }}
            - run:
                  name: Install Dependencies
                  command: mvn dependency:go-offline
            - run:
                  name: Run Tests
                  command: mvn verify
            - save_cache:
                  paths:
                      - ~/.m2
                  key: maven-{{ checksum "/tmp/maven_cache_seed" }}
            - store_test_results:
                  path: target/surefire-reports
            - run:
                  name: Upload Coverage Results
                  command: |
                      bash <(curl -s https://codecov.io/bash) \
                        -n ${CIRCLE_BUILD_NUM} \
                        -t ${CODECOV_TOKEN} \
                        -y .codecov.yml \
                         \
workflows:
    maven:
        jobs:
            - maven
